### ISSUE TITLE
error use null instead of Optional.empty() in class DefaultEntityColumnFactoryChain

### ISSUE THREAD

**Issue by DouglasZillah** [mybatis-mapper/provider#3]
https://github.com/mybatis-mapper/provider/blob/641a2010c680c9fd6788f27bcd4e1637c3daab51/src/main/java/io/mybatis/provider/defaults/DefaultEntityColumnFactoryChain.java#L40
这里返回了null，可能导致在外层方法调用时抛出npe，是否应当使用Optional.empty()。
![image](https://user-images.githubusercontent.com/28729064/172582326-f3473889-9897-4b5e-837b-33856a1f2bfe.png)

**Comment by abel533** [comment]
应该修改，可以PR

**Comment by DouglasZillah** [comment]
已提pr
https://github.com/mybatis-mapper/provider/pull/4
